// Generated by gencpp from file beginner_tutorial/steerAndVelocity.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIAL_MESSAGE_STEERANDVELOCITY_H
#define BEGINNER_TUTORIAL_MESSAGE_STEERANDVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorial
{
template <class ContainerAllocator>
struct steerAndVelocity_
{
  typedef steerAndVelocity_<ContainerAllocator> Type;

  steerAndVelocity_()
    : velocity(0.0)
    , steer(0.0)  {
    }
  steerAndVelocity_(const ContainerAllocator& _alloc)
    : velocity(0.0)
    , steer(0.0)  {
  (void)_alloc;
    }



   typedef float _velocity_type;
  _velocity_type velocity;

   typedef float _steer_type;
  _steer_type steer;





  typedef boost::shared_ptr< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct steerAndVelocity_

typedef ::beginner_tutorial::steerAndVelocity_<std::allocator<void> > steerAndVelocity;

typedef boost::shared_ptr< ::beginner_tutorial::steerAndVelocity > steerAndVelocityPtr;
typedef boost::shared_ptr< ::beginner_tutorial::steerAndVelocity const> steerAndVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator1> & lhs, const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity &&
    lhs.steer == rhs.steer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator1> & lhs, const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorial

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "338cc52c049aa1a1e2dc54d48cdda24b";
  }

  static const char* value(const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x338cc52c049aa1a1ULL;
  static const uint64_t static_value2 = 0xe2dc54d48cdda24bULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorial/steerAndVelocity";
  }

  static const char* value(const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 velocity\n"
"float32 steer\n"
;
  }

  static const char* value(const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
      stream.next(m.steer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct steerAndVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorial::steerAndVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorial::steerAndVelocity_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
    s << indent << "steer: ";
    Printer<float>::stream(s, indent + "  ", v.steer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIAL_MESSAGE_STEERANDVELOCITY_H
